// Generated by diesel_cli
diesel::table! {
    use diesel::sql_types::*;
    use diesel::sql_types::Uuid;
    
    users (id) {
        id -> Uuid,
        username -> Varchar,
        email -> Varchar,
        password_hash -> Varchar,
        created_at -> Timestamp,
        updated_at -> Timestamp,
    }
}

diesel::table! {
    use diesel::sql_types::*;
    use diesel::sql_types::Uuid;
    
    passwords (id) {
        id -> Uuid,
        user_id -> Uuid,
        site_name -> Varchar,
        site_url -> Nullable<Varchar>,
        username -> Varchar,
        encrypted_password -> Varchar,
        encryption_iv -> Varchar,
        notes -> Nullable<Text>,
        created_at -> Timestamp,
        updated_at -> Timestamp,
    }
}

diesel::allow_tables_to_appear_in_same_query!(
    users,
    passwords,
); 